### ISSUE TITLE
update the npm module to point to 

### ISSUE THREAD

**Issue by 4ndr01d3** [ebi-uniprot/biojs-vis-sequence#15]
hey guys,
can you please update the npm module to set the repo to 

> github.com/**ebi-uniprot**/biojs-vis-sequence/ 

instead of 

>github.com/**ljgarcia**/biojs-vis-sequence ?

I think BioJS is still looking for it in the old repo URL and is not able to solve the HTTP redirect. Maybe that is something to consider in the BioJS registry

**Comment by wilzbach** [comment]
Oh I didn't know that I even have access to this. If someone wants to have access to npm, let me know your username there

**Comment by ljgarcia** [comment]
Should be working now.
